### ISSUE TITLE
TP 1 completed

### ISSUE THREAD

**Issue by sofianebelaribi** [PolytechLyon/2019-isi3-graph-batton_belaribi#1]
Hi,
We've finished and completed our first ISI3 practical work ! 🎉
Would you mind checking it out ? 🔍
Thanks in advance !

**Comment by Slashgear** [comment]
- 👍 Rapport complet

- Itérateur bien compris

- [ ] Pourquoi définir cette fonction est inutile ?

https://github.com/PolytechLyon/2019-isi3-graph-batton_belaribi/blob/3d3becbbfb1d8394deb290efef0c2bee624704af/src/main/java/graph/UndirectedGraph.java#L24-L26

**Comment by sofianebelaribi** [comment]
@Slashgear

Exact ! 
Nous pensions qu'il fallait réimplémenter les méthodes dans la nouvelle classe à cause du Design Pattern **Adapter**. Mais en réalité, vu que nous générons une instance d'**Igraph** (qui nous permet du coup d'utiliser un **Iterator** sur les deux types de Graph : **Graph** et **UndirectedGraph**) ça n'est pas utile et est une duplication de code inutile (**DRY ?** )

Commit de correction : 887da4527afd558f7aec0451397b1360b0cc7ec2
